
server:
  port: 9000

logging:
  level:
    org:
      hibernate:
        SQL: trace


spring:
  http:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://192.168.224.130:3306/idziak_db
    username: idziak
    password: idziak
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddlAuto: create
        formatSql: true
        showSql: true
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect